<script src="<?php echo $host; ?>/public.js"></script>
<script>
var user;
var pwd;
var language='french';
</script>
<script src="<?php echo $host; ?>/french/string.js"></script>
<script src="<?php echo $host; ?>/get_status.cgi"></script>     
<!--<iframe marginheight="0" marginwidth="0" width="100%" height="100%" frameborder="0" src="<?php echo $host; ?>login.htm"></iframe>-->       
<frameset rows="0%,100%" frameborder="no" border="0" framespacing="0">	      
<frame name="vars" src="<?php echo $host; ?>/vars.htm" frameborder="no">  
</frame>	    
<frame name="main" frameborder="no">
</frame>   
</frameset>   
<noframes>   
</noframes>
</html>