<div align="center"> 
  <img id="live" src=""> <br /> 
  <div id="cambuttons" class="cambuttons"> 
    <input name="btnDown"      type="button" class=button id="btnDown"      onClick="ptzDownSubmit()"   value="Down"/> 
    <input name="btnUP"        type="button" class=button id="btnUP"        onClick="ptzUpSubmit()"     value="Up"/> 
    <input name="btnLeft"      type="button" class=button id="btnLeft"      onClick="ptzLeftSubmit()"   value="Left"/> 
    <input name="btnRight"     type="button" class=button id="btnRight"     onClick="ptzRightSubmit()"  value="Right"/> 
    <!--<input name="btnRefresh"   type="button" class=button id="btnRefresh"   onClick="location.reload()" value="Refresh"/>--> 
    <input name="btnswitchon"  type="button" class=button id="btnswitchon"  onClick="OnSwitchOn()"      value="On"> 
    <input name="btnswitchoff" type="button" class=button id="btnswitchoff" onClick="OnSwitchOff()"     value="Off"> <br /> 
<script>document.write(_ptz_pos);</script> 
    <input name="btmyzw1" type="button" class=button id="btmyzw1" onClick="callcmd(31)" value=" 1 "/> 
    <input name="btmyzw2" type="button" class=button id="btmyzw2" onClick="callcmd(33)" value=" 2 "/> 
    <input name="btmyzw3" type="button" class=button id="btmyzw3" onClick="callcmd(35)" value=" 3 "/> 
    <input name="btmyzw4" type="button" class=button id="btmyzw4" onClick="callcmd(37)" value=" 4 "/> 
    <input name="btmyzw5" type="button" class=button id="btmyzw5" onClick="callcmd(39)" value=" 5 "/>
  </div>
</div>
<br />
<br />